name = "Bennu"
uuid = "a1f7094c-8d14-434f-a772-7144e1a1c6c0"
authors = ["Lucas C Wilcox <lucas@swirlee.com> and contributors"]
version = "0.0.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
StructArrays = "0.5"
Tullio = "0.2"
julia = "^1.5"
